### ISSUE TITLE
Refactor back-end communications to use Pacifica Web API calls

### ISSUE THREAD

**Issue by kauberry** [EMSL-MSC/pacifica-reporting#2]
Currently, the reporting system relies upon SQL queries directly into the PostgreSQL backend database to retrieve aggregate data for reporting. The Pacifica metadata API has been designed to abstract this away from the reporting and status monitoring websites, and we will be switching over to it in the near future. Need a branch to experiment on for this.

**Comment by dmlb2000** [comment]
I would like to copy this issue to a milestone... If you want to break this issue up into separate issues for easier tracking go ahead... just apply them to the same milestone as this issue.
