### ISSUE TITLE
SQLite concurrency issues causing trouble with dev/prod

### ISSUE THREAD

**Issue by kauberry** [EMSL-MSC/pacifica-reporting#61]
Database locking issues are causing Ajax calls to the reporting info database to throw errors. This is only going to get worse when we have multiple users hitting reporting at once. Need to switch back to using Postgres on our real systems.

**Comment by dmlb2000** [comment]
So, what's the reason for the Ajax calls reporting errors? Are the users being impatient and clicking too much?

**Comment by kauberry** [comment]
Yes. I'm clicking too fast.

The option settings calls are atomic and hit pretty quickly one after another whenever the user changes the start/end dates. I could fix that by coalescing the calls, but that won't fix it when we have multiple users hitting it at once.

Another possible option would be to have separate SQLite database files for each user, but that's messier than just letting PG handle the right way.

Ken


Ken J. Auberry, <mailto:Kenneth.Auberry@pnnl.gov> Senior Research Scientist
Instrument Development Laboratory
Environmental Molecular Sciences Laboratory<http://www.emsl.pnnl.gov/>
email: Kenneth.Auberry@pnnl.gov<mailto:Kenneth.Auberry@pnnl.gov>
tel: <tel:+1-509-371-6442> 509<tel:509.371.6442>.<tel:509.371.6442>371<tel:509.371.6442>.<tel:509.371.6442>6442<tel:509.371.6442>



On May 9, 2017, at 3:17 PM, David Brown <notifications@github.com<mailto:notifications@github.com>> wrote:


So, what's the reason for the Ajax calls reporting errors? Are the users being impatient and clicking too much?
